services:
  - type: web
    name: flutter-chatbot
    env: static
    staticPublishPath: ./build/web
    buildCommand: |
      # Download and install Flutter
      export FLUTTER_HOME="$HOME/flutter"
      if [ ! -d "$FLUTTER_HOME" ]; then
        curl -L https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.32.2-stable.tar.xz | tar -xJ -C $HOME
      fi
      export PATH="$PATH:$FLUTTER_HOME/bin"
      
      # Configure Flutter
      flutter config --enable-web --no-analytics
      flutter doctor --android-licenses || true
      
      # Build the app
      flutter clean
      flutter pub get
      flutter build web --release
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
